baseURL = "https://devsanso.github.io/Sunken.github.io/"
languageCode = "en-us"
title = "Sunken Ahn Blog"
theme = "PaperMod"




[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 20



[taxonomise]
    tag = "tags"



[params.homeInfoParams]
Title = "Hi, Welcome My Blog"
Content = "편안하게 들렸다 가세요"




[outputs]
home = [ "HTML", "RSS", "JSON" ]